"""sincronizar models

Revision ID: 5bddc52a7559
Revises: bf2d89202a14
Create Date: 2025-12-03 15:12:38.877654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bddc52a7559'
down_revision = 'bf2d89202a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_agendamentos_prestador',   # ← nome obrigatório
            'user',
            ['prestador_id'],
            ['id']
        )
        batch_op.drop_column('prestador')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('foto', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('foto')
        batch_op.drop_column('descricao')

    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prestador', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_agendamentos_prestador', type_='foreignkey')

    # ### end Alembic commands ###
