"""add prestador fields

Revision ID: 83b7e92e9e73
Revises: 5bddc52a7559
Create Date: 2025-12-03 17:09:19.209483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b7e92e9e73'
down_revision = '5bddc52a7559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('descricao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('foto')
        batch_op.drop_column('descricao')
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
